version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: prisma-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onsite
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-backend
    ports:
      - "3098:3098"
    depends_on:
      - mysql
    env_file:
      - .env
    command: ["sh", "-c", "npx prisma migrate deploy && node index.js"]

volumes:
  mysql_data:
